feat: Stricter enforcement and specific file exclusions
wilhelmer/mkdocs-unused-files pull request #4
Opened 2023-01-09 05:16 UTC by butler54

This PR introduces two changes - note that it will result in overall behaviour changes and may be a major version bump:

1. Changes the level from INFO to WARNING. This ensures when `mkdocs -s` is used that the process will error out of unused files are found.
2. Introduces an `excluded_files` flag. 

I made a couple of minor formatting changes on the way through as well.

Closes: #3

2023-01-09 08:13 UTC, wilhelmer commented
Thanks for contributing! I was already thinking about adding file or file type exclusions, so that change is very welcome.

I'm not sure about the severity level change though. In MkDocs, 1) when a page is referenced in the nav, but can't be found in the documentation files, a WARNING message is displayed. But vice versa, i.e., 2) when a page is found in the documentation files but not referenced in the nav, an INFO message is displayed.

To me, case 2) is much more similar to what this plugin does. It **informs** the user that something in the project could be improved, but the output is still functional. Case 1) is a more serious issue, since the navigation will have broken links.

I can see that you may want to use the `-s` flag to enforce a "clean" repository. But I'd rather make this optional, i.e., introduce something like a `severity_level` option.

2023-01-10 04:13 UTC, butler54 commented
> Thanks for contributing! I was already thinking about adding file or file type exclusions, so that change is very welcome.
> 
> I'm not sure about the severity level change though. In MkDocs, 1) when a page is referenced in the nav, but can't be found in the documentation files, a WARNING message is displayed. But vice versa, i.e., 2) when a page is found in the documentation files but not referenced in the nav, an INFO message is displayed.
> 
> To me, case 2) is much more similar to what this plugin does. It **informs** the user that something in the project could be improved, but the output is still functional. Case 1) is a more serious issue, since the navigation will have broken links.
> 
> I can see that you may want to use the `-s` flag to enforce a "clean" repository. But I'd rather make this optional, i.e., introduce something like a `severity_level` option.

I'm happy to add that as well. Just in terms of naming - perhaps to keep it inline with mkdocs itself it could be a boolean for `strict` with a default of false?

2023-01-10 07:14 UTC, wilhelmer commented
That's fine with me. Other plugins also have this option, e.g., [mkdocs-awesome-pages](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/). And yes, it should default to false.

2023-01-11 00:05 UTC, butler54 commented
Great. I'm also putting this in draft as I discovered a bug today with nested paths.

2023-01-11 00:33 UTC, butler54 commented
Should be good to review now.

2023-01-11 09:03 UTC, wilhelmer requested changes
Code looks good to me, only minor documentation changes.

2023-01-11 09:03 UTC, wilhelmer commented on README.md
> +WARNING -  The following files exist in the docs directory, but may be unused:
Please revert this change, as INFO is still the default.

2023-01-11 09:03 UTC, wilhelmer commented on README.md
> +* `strict`: A boolean, defaulting to `false`, which elevates the log level to warning. This allows unused-files to be combined with `mkdocs` strict flag (`-s`) to abort a build if unused files exist.
Please also add both options to the sample in the "Installation" section, e.g.:

```yaml
plugins:
  - search
  - unused_files:
      dir: images
      file_types:
        - png
        - jpg
        - svg
      excluded_files:
        - css/favicon.png
      strict: true
```

2023-01-13 09:16 UTC, butler54 commented
Should be good to go!

Really appreciate the prompt reviews.

2023-01-16 07:57 UTC, merged